version : '2'
services:
  influxdb:
    image: "influxdb:latest"
    container_name : "influxdb"
    ports:
      - "8086:8086"
      - "8083:8083"
    expose:
      - "8086"
      - "8083"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - "influxdb"
    volumes:
      - ./data/grafana:/var/lib/grafana
