@default_files = ('thesis.tex');

sub makeglossaries {
    system( "makeglossaries '$_[0]'" );
}
add_cus_dep( "glo", "gls", 0, "makeglossaries" );
add_cus_dep( "acn", "acr", 0, "makeglossaries" );
push @generated_exts, "glo", "gls", "glg";
push @generated_exts, "acn", "acr", "alg";

$latex = 'texfot latex -interaction=nonstopmode -shell-escape';
$pdflatex = 'texfot pdflatex -interaction=nonstopmode -shell-escape';
$clean_ext = "bbl glo lol ist run.xml synctex.gz _minted-thesis auto"
